apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  labels:
    app: ${{ values.name }}
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - name: http
      port: 80
      targetPort: ${{ values.port }}
  type: ClusterIP
